import type { ElementDef } from './elements';
import icons from './iconElements.json';

/* Open-source decoration elements — Phosphor Icons (MIT licence), picked for
 * family albums and generated by tools/album_templates/build_icon_elements.mjs. */

interface IconEntry { id: string; name: string; weight: string; d: string; tags: string[] }

let cache: ElementDef[] | null = null;

export function iconElements(): ElementDef[] {
  if (cache) return cache;
  cache = (icons as IconEntry[]).map((icon) => ({
    id: icon.id,
    name: icon.name,
    group: 'icons',
    kind: 'path',
    d: icon.d,
    // Phosphor draws every icon on the same 256-unit square
    bounds: { x: 0, y: 0, width: 256, height: 256 },
    fill: '#ffffff',
    keywords: `${icon.name} ${icon.tags.join(' ')} ${icon.weight === 'thin' ? 'קו דק' : 'מלא'}`,
  }));
  return cache;
}
